apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubezero-k0
  namespace: kubezero
spec:
  destination:
    server: https://192.168.178.48:56408
    namespace: kubezero
  project: management
  source:
    repoURL: https://github.com/wazery/kubezero
    targetRevision: main
    path: registry/management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true