apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubezero-management
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/kubezero/kubezero
    targetRevision: HEAD
    path: stacks/management/overlays/default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true