---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controller
  namespace: kubezero
spec:
  description: Platform controller resources
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: kubezero
    - server: https://kubernetes.default.svc
      namespace: crossplane-system
  sourceRepos:
    - https://github.com/wazery/kubezero
